<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_CylinderTemp" Id="{853695ea-0a11-40ec-9858-19484fa1f60c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CylinderTemp EXTENDS FB_CylinderBase
VAR_INPUT
	fTempCurrent		AT %I*		:		LREAL;		// Hardware input signal: cylinder temperature
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CylinderTemp">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>